## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
coveralls: true
codecov: true
os:
  - osx
  - linux
  - windows
julia:
  - 1.0
  - 1
notifications:
  email: false
git:
  depth: 99999999